name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B clean test -Dspring.profiles.active=ci

  integration-tests:
    runs-on: ubuntu-latest
    needs: build-and-unit-tests
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: emil
          MYSQL_DATABASE: demo_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" -uroot -pemil --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done
      - run: mvn -B verify -Dspring.profiles.active=ci
