name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B clean test -Dspring.profiles.active=ci

  integration-tests:
    runs-on: ubuntu-latest
    needs: build-and-unit-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B verify -Dspring.profiles.active=ci

  deploy:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build JAR
      - run: mvn -B clean package -DskipTests

      # Login to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t emilpopa24/spring-boot-ci-demo:latest .
          docker push emilpopa24/spring-boot-ci-demo:latest
