name: Java CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # ------------------------------
  # Job 1: Build + Unit Tests
  # ------------------------------
  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B clean test -Dspring.profiles.active=ci

  # ------------------------------
  # Job 2: Integration Tests (H2)
  # ------------------------------
  integration-tests:
    runs-on: ubuntu-latest
    needs: build-and-unit-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B verify -Dspring.profiles.active=test
